// <auto-generated />
using DL.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190708235540_MonsterRewards")]
    partial class MonsterRewards
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DL.Application.Domain.Monsters.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Power")
                        .HasColumnName("power")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("monsters");
                });

            modelBuilder.Entity("DL.Application.Domain.Monsters.Reward", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonsterId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Value")
                        .HasColumnName("value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MonsterId");

                    b.ToTable("rewards");
                });

            modelBuilder.Entity("DL.Application.Domain.Monsters.Reward", b =>
                {
                    b.HasOne("DL.Application.Domain.Monsters.Monster", "Monster")
                        .WithMany("Rewards")
                        .HasForeignKey("MonsterId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
