// <auto-generated />

using DL.Data.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DL.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190707191435_AddsMonsters")]
    partial class AddsMonsters
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("DL.Application.Domain.Monsters.Monster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnName("name")
                        .HasColumnType("VARCHAR(30)");

                    b.Property<int>("Power")
                        .HasColumnName("power")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("monsters");
                });
#pragma warning restore 612, 618
        }
    }
}
